# Generated by Django 3.1.7 on 2021-03-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatepages', '0004_auto_20210330_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privacyandpolicy',
            options={'verbose_name': 'Գաղտնիության քաղաքականություն', 'verbose_name_plural': 'Գաղտնիության քաղաքականություն'},
        ),
    ]
