# Generated by Django 3.1.7 on 2021-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_hy',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_ru',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_hy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
