# Generated by Django 3.1.7 on 2021-03-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210325_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Բաժիններ', 'verbose_name_plural': 'Բաժիններ'},
        ),
    ]
