# Generated by Django 3.1.7 on 2021-03-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210330_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_hy',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_hy',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Արտադրող երկիր'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_hy',
            field=models.CharField(max_length=150, null=True, verbose_name='Արտադրող երկիր'),
        ),
        migrations.AddField(
            model_name='product',
            name='country_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Արտադրող երկիր'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Արտադրող'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_hy',
            field=models.CharField(max_length=150, null=True, verbose_name='Արտադրող'),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Արտադրող'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Հզորություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_hy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Հզորություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='power_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Հզորություն'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_in_coll_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Քանակը հավաքածուում'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_in_coll_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Քանակը հավաքածուում'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_in_coll_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Քանակը հավաքածուում'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Տեսակ'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_hy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Տեսակ'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Տեսակ'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ծավալ'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_hy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ծավալ'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ծավալ'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Քաշ'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_hy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Քաշ'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Քաշ'),
        ),
    ]
