# Generated by Django 3.1.7 on 2021-03-31 11:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210330_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Անուն')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Անուն')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Անուն')),
                ('name_hy', models.CharField(max_length=150, null=True, verbose_name='Անուն')),
                ('url', models.URLField(verbose_name='Հղում')),
                ('image', models.FileField(upload_to='offer_images/', verbose_name='Նկար')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Նկարագրություն')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Նկարագրություն')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Նկարագրություն')),
                ('description_hy', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Նկարագրություն')),
            ],
            options={
                'verbose_name': 'Հատուկ առաջարկ',
                'verbose_name_plural': 'Հատուկ առաջարկ',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
