# Generated by Django 3.1.7 on 2021-03-31 11:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210331_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='Նկար')),
                ('context', ckeditor.fields.RichTextField(verbose_name='Նկարագրություն')),
                ('context_en', ckeditor.fields.RichTextField(null=True, verbose_name='Նկարագրություն')),
                ('context_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Նկարագրություն')),
                ('context_hy', ckeditor.fields.RichTextField(null=True, verbose_name='Նկարագրություն')),
                ('url', models.URLField(verbose_name='Հղում')),
            ],
            options={
                'verbose_name': 'Սլայդեր',
                'verbose_name_plural': 'Սլայդեր',
            },
        ),
    ]
