# Generated by Django 3.1.7 on 2021-04-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210401_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=150, verbose_name='Արտադրող երկիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Արտադրող երկիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_hy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Արտադրող երկիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Արտադրող երկիր'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured',
            field=models.CharField(blank=True, max_length=150, verbose_name='Արտադրող'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Արտադրող'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_hy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Արտադրող'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Արտադրող'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_hy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_in_coll',
            field=models.CharField(blank=True, max_length=50, verbose_name='Քանակը հավաքածուում'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_in_coll_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Քանակը հավաքածուում'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_in_coll_hy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Քանակը հավաքածուում'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty_in_coll_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Քանակը հավաքածուում'),
        ),
        migrations.AlterField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Դիտումների քանակ'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color', verbose_name='Գույն'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Գին'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='product_code',
            field=models.CharField(max_length=15, verbose_name='Ապրանքի կոդ'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='Զեղչված գին'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='size',
            field=models.CharField(max_length=50, verbose_name='Չափս'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='size_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Չափս'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='size_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Չափս'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='size_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Չափս'),
        ),
    ]
