# Generated by Django 3.1.7 on 2021-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210401_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_hy',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Անուն'),
        ),
    ]
