# Generated by Django 3.1.7 on 2021-04-01 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210401_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
