# Generated by Django 3.1.7 on 2021-04-01 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20210401_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantimages',
            options={'verbose_name': 'Ապրանքների նկարներ', 'verbose_name_plural': 'Ապրանքների նկարներ'},
        ),
    ]
