# Generated by Django 3.1.7 on 2021-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210402_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='image',
            field=models.FileField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductVariantImages',
        ),
    ]
