# Generated by Django 3.1.7 on 2021-04-02 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20210402_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariants')),
            ],
            options={
                'verbose_name': 'Ապրանքների նկարներ',
                'verbose_name_plural': 'Ապրանքների նկարներ',
            },
        ),
    ]
