# Generated by Django 3.1.7 on 2021-04-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productvariantimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariants',
            name='image',
        ),
        migrations.AddField(
            model_name='productvariantimages',
            name='image',
            field=models.FileField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
