# Generated by Django 3.1.7 on 2021-04-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20210402_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimages',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariants'),
        ),
    ]
