# Generated by Django 3.1.7 on 2021-04-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20210403_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=150, verbose_name='Հզորություն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Հզորություն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_hy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Հզորություն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Հզորություն'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort',
            field=models.CharField(blank=True, max_length=150, verbose_name='Տեսակ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Տեսակ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_hy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Տեսակ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Տեսակ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ծավալ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ծավալ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_hy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ծավալ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ծավալ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=150, verbose_name='Քաշ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Քաշ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_hy',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Քաշ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Քաշ'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='size',
            field=models.CharField(max_length=150, verbose_name='Չափս'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='size_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Չափս'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='size_hy',
            field=models.CharField(max_length=150, null=True, verbose_name='Չափս'),
        ),
        migrations.AlterField(
            model_name='productvariants',
            name='size_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Չափս'),
        ),
    ]
