# Generated by Django 3.1.7 on 2021-04-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20210403_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='filter_price',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
