# Generated by Django 3.1.7 on 2021-04-11 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0006_auto_20210402_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hy', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Քաղաք/գյուղ',
                'verbose_name_plural': 'Քաղաք/գյուղ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('all_total_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('order_id_ecc', models.CharField(blank=True, max_length=80, null=True)),
                ('order_status_code', models.CharField(blank=True, max_length=80, null=True)),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=60)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('delivery_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comments', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.city')),
            ],
            options={
                'verbose_name': 'Պատվերներ',
                'verbose_name_plural': 'Պատվերներ',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Պատվերի կարգավիճակներ',
                'verbose_name_plural': 'Պատվերի կարգավիճակներ',
            },
        ),
        migrations.CreateModel(
            name='PaymentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Վճարային համակարգեր',
                'verbose_name_plural': 'Վճարային համակարգեր',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hy', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ru', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Մարզեր',
                'verbose_name_plural': 'Մարզեր',
            },
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=120)),
                ('product_price', models.PositiveIntegerField(blank=True, default=0)),
                ('product_image', models.ImageField(blank=True, upload_to='')),
                ('item_total_price', models.PositiveIntegerField(blank=True, default=0)),
                ('qty', models.PositiveIntegerField(blank=True, default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.orderstatuses'),
        ),
        migrations.AddField(
            model_name='order',
            name='payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.paymenttypes'),
        ),
        migrations.AddField(
            model_name='order',
            name='state_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.state'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.state'),
        ),
    ]
