# Generated by Django 3.1.7 on 2021-04-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210411_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttypes',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PaymentTypeIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='payment_icons')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.paymenttypes')),
            ],
        ),
    ]
