# Generated by Django 3.1.7 on 2021-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20210413_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttypeicons',
            name='icon',
            field=models.FileField(upload_to='payment_icons'),
        ),
    ]
